### ISSUE TITLE
Incorrect import path when generating a new client into a "v2" directory

### ISSUE THREAD

**Issue by quartzmo** [googleapis/gapic-generator-go#1002]
In google-cloud-go, run `genbot` locally to generate a new client into a "v2" directory. 

1. Edit `internal/gapicgen/generator/config.go`. Add `/v2` before api version in the import path:

```
ImportPath:            "cloud.google.com/go/recaptchaenterprise/v2/apiv1",
```

1. In `internal/gapicgen`, run genbot: 

```
$ go run cloud.google.com/go/internal/gapicgen/cmd/genbot -local -gocloud-dir /Users/chrisdsmith/oss/google-cloud-go -only-gapics -gapic=cloud.google.com/go/recaptchaenterprise/v2/apiv1
```

1.  Inspect the generated file `recaptchaenterprise/v2/apiv1/version.go`:

    Got: `import "cloud.google.com/go/recaptchaenterprise/internal"`
    Want: `import "cloud.google.com/go/recaptchaenterprise/v2/internal"`

**Comment by noahdietz** [comment]
The `version.go` file is actually generated by the `internal/gapicgen` pipeline [here](https://github.com/googleapis/google-cloud-go/commit/341e0df1e44480706180cc5b07c49b3cee904095) :) The gapic-generator-go doesn't generate this file today.

**Comment by quartzmo** [comment]
Ooops! Thank you.
