### ISSUE TITLE
Do we support generating libraries that use google.golang.org/genproto/googleapis/cloud/common?

### ISSUE THREAD

**Issue by codyoss** [googleapis/gapic-generator-go#1039]
If we need to add an import do to do, we should do so soonish. There will soon be apis that require the operationMetadta.

Internal CL: 453854177

**Comment by noahdietz** [comment]
Yep we support this type, and it is currently used in the `filestore` Go GAPIC: https://github.com/googleapis/google-cloud-go/blob/main/filestore/apiv1/cloud_filestore_manager_client.go#L791-L799
