### ISSUE TITLE
gengapic: REGAPIC missing return statement with google.api.HttpBody specified as response type

### ISSUE THREAD

**Issue by noahdietz** [googleapis/gapic-generator-go#1051]
For REGAPIC clients, missing return statement in generated method ([here](https://github.com/googleapis/gapic-generator-go/blob/2108164e63942257b038402424de4ad953388e0b/internal/gengapic/genrest.go#L1131)) when `google.api.HttpBody` is the response type for the RPC.

Repro with `google/cloud/retail/v2:retail_go_gapic` (bazel) or `cloud.google.com/go/retail/apiv2` (internal/gapicgen).

**Comment by noahdietz** [comment]
@quartzmo let's tackle this one over GVC together :)

**Comment by vam-google** [comment]
The following is the list of affected APIs:

```
//google/cloud/apigeeregistry/v1
//google/cloud/recommendationengine/v1beta1
//google/cloud/retail/v2
//google/cloud/retail/v2alpha
//google/cloud/retail/v2beta
```
