### ISSUE TITLE
gapic: doc.go refers to "NewClient" instead of service-specific constructors.

### ISSUE THREAD

**Issue by timburks** [googleapis/gapic-generator-go#1077]
Reviewing [this code](https://github.com/googleapis/gapic-generator-go/search?q=New%25sClient), it appears that client constructors include the names of their associated services.

But [here](https://github.com/googleapis/gapic-generator-go/blob/a6c0c818b67975c14ebab052c7bf37d45548baff/internal/gengapic/doc_file.go#L100), a comment in generated `doc.go` refers to an initializer named `NewClient`. Is that an obsolete reference?

**Comment by noahdietz** [comment]
Not an obsolete reference, but a naive one. It should be updated to include the `%s` like the first link mentions.

The name that (potentially) goes in there is a reduction of the proto service name i.e. if the package is `language` and the proto service is named `Language` the factory method for that client will be `NewClient`, but if the package is named `language` and the proto service is named `FooBar`, the factory method would be `NewFooBarClient`. This prevents stuttering like `language.NewLanguageClient`.

You'll notice in your first link that the value given to the `%s` is something like `servName` - that is the reduced service name. Would happily take a fix for this, but also perhaps @quartzmo would be interested in fixing it. Either way, let us know @timburks, thanks for catching that.

**Comment by noahdietz** [comment]
@quartzmo any interest in making this generated doc fix?
