### ISSUE TITLE
gapic: support deprecated as a release-level option value.

### ISSUE THREAD

**Issue by noahdietz** [googleapis/gapic-generator-go#1095]
Moving https://github.com/googleapis/google-cloud-go/issues/5941 to this repo. We'd like to support a `deprecated` value for the `release-level` option. Using this value should result in generated package level documentation indicating that the package as a whole is deprecated.

**Comment by julieqiu** [comment]
Fixed in https://github.com/googleapis/gapic-generator-go/pull/1390
