### ISSUE TITLE
chore: modify .gitignores with Respect to the IDEs 

### ISSUE THREAD

**Issue by sandipbhuyan** [googleapis/gapic-generator-go#110]
I think at the current state of the application the gitignores are note configured for the IDEs(jetbrains, vscodes, vim etc). I am specifying some IDEs rest IDE user can add accordingly

## Gitignores
- [ ] Jetbrains
- [ ] vim

**Comment by noahdietz** [comment]
To be clear, you want to add the relevant IDEA configuration files for Jetbrains and vim to the `.gitignore`? If so, please go ahead

**Comment by sandipbhuyan** [comment]
Yes, thanks
