### ISSUE TITLE
gengapic: move top-level package docs link to more prominent position

### ISSUE THREAD

**Issue by noahdietz** [googleapis/gapic-generator-go#1140]
The top-level Go Client docs contain a lot of information that applies to most/all of the clients it contains: https://pkg.go.dev/cloud.google.com/go.

In GAPICs, the link to this documentation is kind of buried. It would be better if it had its own header or a more prominent position so that it is easier to find. Currently, it is the last thing in the package level documentation under a more specific header.

![image](https://user-images.githubusercontent.com/6644735/191130132-e54f0228-beb0-401b-8d40-159c83149c27.png)

**Comment by noahdietz** [comment]
Let's use the new hyperlinked text godoc feature as well.

**Comment by quartzmo** [comment]
https://tip.golang.org/doc/comment#links
