### ISSUE TITLE
[Feature] Golang interface support for the generated structs

### ISSUE THREAD

**Issue by HuairuoYang** [googleapis/gapic-generator-go#1163]
Hi team!

I am using this tool to build clients for REST/GRPC and I think this is a great tool to use!

However during my implementation and actual usage, I found that just the generated `Client` struct is not enough for developers to mock and use. 

And it is more difficult for `longrunning.Operations`. Those `longrunning.Operation` will be generated as `*Operations struct` which cannot be mocked (because they are structs). And with the private interface we cannot even adjust the parameter.

### Example:
1.
For methods returning `longrunning.Operation`, a struct like this will be generated that has methods `Wait`, `Poll`:
```
type ExampleMethodOperation struct {
	lro      *longrunning.Operation
	pollPath string
}
```

And I really loved this feature that simplifies things but I am thinking that could we also have the interface generated for them?
Like 
```
// ExampleMethodOperation in an interface for interacting with longrunning ExampleMethodOperation.
type ExampleAPIOperation interface {
	Name() string
	Done() bool
	Metadata() (*Metadata, error)
	Wait(ctx context.Context, opts ...gax.CallOption) (*response, error)
	Poll(ctx context.Context, opts ...gax.CallOption) (*response, error)
}
```
I am now manually creating this interface every time a new API is added.

2.
Also, taking the [google cloud language example](https://github.com/googleapis/google-cloud-go/tree/main/language/apiv1): If we would love to test, mock, or wrap around this interface, we would need to wrap it around with another layer of interface and this make things really duplicated.
In `generated_client.go` we have:
```
type Client struct {
	internalClient internalClient
	CallOptions *CallOptions
}
```
And now we are doing this:
```
type ClientInterface interface{ //Copy-Paste all methods for Client}

// MyClient implements the `PublicClient` and do the extra log before/after route all the calls to `Client`
type MyClient struct {// contains a Client}
```

But ideally I am thinking that if we could have this interface generated in the `generated_client.go` 
```
type ClientInterface interface{...}

// Client will implement the ClientInterface
type Client struct {
	InternalClient internalClient
	CallOptions *CallOptions
}
```
So that we would be able to get rid of all the manual steps for re-creating the interface on developer side?

So that I am thinking that ideally everything can go through interfaces, instead of pointers of structs, or at least they can be generated for users?
This will provide perfect auxiliary and it will provide great developer experience!
Thanks for making this better!

**Comment by HuairuoYang** [comment]
In addition, I can use this tool for the interface generation https://github.com/vburenin/ifacemaker
But this can only generate separate interfaces for `longrunning.Operation` and `Client`.
I still need a layer of interface to let the `Client` return interfaces for `longrunning.Operation`

**Comment by noahdietz** [comment]
Hey @HuairuoYang thanks for the request. Unfortunately, I don't think we want to expose the client interface on the package surface. The problem is that adding a method to an interface is a backwards incompatible change in Go. So when a new RPC is published for Google APIs, for example, a new method would be added to the interface, breaking any existing code that hasn't implemented it yet. This would make everyone's testing code, for example, very brittle.

@codyoss may have other ideas of how to mock things without needing to mock the GAPIC interface. It's a question that's been asked before.

Alternatively, you could do some post-processing on your own generated code and export the `internal....Client` by simply replacing it with the exported version `Internal...Client`.

**Comment by HuairuoYang** [comment]
Thanks @noahdietz !
