### ISSUE TITLE
x/net/context is being used instead of context

### ISSUE THREAD

**Issue by jadekler** [googleapis/gapic-generator-go#129]
See: https://github.com/google/go-genproto/pull/118 `iam_policy.pb.go`

**Comment by noahdietz** [comment]
@jadekler Isn't go-genproto generated using the standard Go protobuf/gRPC plugin? 

This repo is for the GAPIC micro-generator plugin. I don't think it is used in the generation of `pb.go` files. Nor is `googleapis/gapic-generator`.

**Comment by jadekler** [comment]
Ah wait, yeah, you're totally right. Closing and investigating some more.
