### ISSUE TITLE
we should remove the use of compiling regex from hotpath of api calls

### ISSUE THREAD

**Issue by codyoss** [googleapis/gapic-generator-go#1376]
https://github.com/googleapis/gapic-generator-go/blame/b78472cc517c0f37582ee69fec21fdf992aca92b/internal/gengapic/gengapic.go#L349

I noticed this in a recent PR and it shows up for some performance sensitive API calls like that in GCS. Let's see if we can refactor this out and do a simple printf style formatting.

**Comment by noahdietz** [comment]
We kind of have this already requested in #1304

Do you want to close this as a dupe and add your comments there?

>  and do a simple printf style formatting.

The regex is used for matching/parsing the field values based on the `google.api.routing` annotation, so I'm not sure what this suggestions is referring to?

**Comment by codyoss** [comment]
@noahdietz Added a note. Opened this quickly so I did not forget without looking at the why. Maybe it needs to be a regex but it can be moved to a call(1) cost vs call(n) cost. Mentioned this in the other issue.
