### ISSUE TITLE
SampleGen: response handling: support indexing into repeated fields

### ISSUE THREAD

**Issue by hzyi-google** [googleapis/gapic-generator-go#180]
See: https://github.com/hzyi-google/sample-staging/blob/df0e9d64782c6d3fc61be167c7129a6e614d29d3/20190821/go-output/speech_transcribe_sync_gcs.go#L58

**Comment by vchudnov-g** [comment]
Could you change this title to make the request very clear? I assume it's "SampleGen: response handling: support indexing into repeated fields"

**Comment by hzyi-google** [comment]
Please feel free to go ahead and just change it :)

**Comment by vchudnov-g** [comment]
I wasn't 100% sure about your intention ;-)
