### ISSUE TITLE
bazel: add sample-only option to go_gapic_library

### ISSUE THREAD

**Issue by noahdietz** [googleapis/gapic-generator-go#233]
The `sample-only` plugin option disables generation of the GAPIC and only runs sample gen. This option should be reflected in the go_gapic_library macro

**Comment by idoqo** [comment]
Hi, is this up for contribution? I would love to pick it up with some pointers.

**Comment by noahdietz** [comment]
Sure! If you look at the [existing macro](https://github.com/googleapis/gapic-generator-go/blob/8044a925875569bb639be91511a2106a9900c0d4/rules_go_gapic/go_gapic.bzl) you'll see that each of the protoc plugin options are available for use in the macro definition.

For example:
The value of `importpath` [attribute](https://github.com/googleapis/gapic-generator-go/blob/8044a925875569bb639be91511a2106a9900c0d4/rules_go_gapic/go_gapic.bzl#L21) is used to [supply](https://github.com/googleapis/gapic-generator-go/blob/8044a925875569bb639be91511a2106a9900c0d4/rules_go_gapic/go_gapic.bzl#L42) the `go-gapic-package` plugin option.

The `sample-only` plugin option is essentially a boolean flag - if `--go_gapic_opt=sample-only` exists, client generation is short-circuited. 

Thus, the macro attribute should be **optional** with a default value of `false` and should only be supplied to the generator (in bazel, the proto_custom_library rule) if `sample-only == true`.

Worth noting that this option is only really useful if the repeated `sample` plugin option is also provided, which is not implemented for the bazel rule either. They should probably be implemented together. 

A `samples` attribute would be a list of Labels (optional, defaults to empty list) that are the paths to sample gen config files. If the list is non-empty, each one would be added to the `plugin_file_args` dictionary with the path (the list item) being used as the **key,** and the plugin option name `sample` being the **value**. This will result in the plugin being invoked with multiple `--go_gapic_opt="sample=path/to/my/sample/config"`. See the `grpc_service_config` attribute as an example of this for a single file.

**Comment by idoqo** [comment]
Thanks @noahdietz. I've made some changes on my [fork here](https://github.com/idoqo/gapic-generator-go/commit/f2ca3743c24f52d64176daed1d942c1d356728c0), but figured I should hold off on creating a PR as I'm not sure how correct it is.

**Comment by noahdietz** [comment]
It's looking great! I left a single comment about the `sample-only` flag. I will push a small repo to my personal account that you can fork and use to test the `go_gapic_library` rule. I'll notify you here when that happens.

**Comment by noahdietz** [comment]
Clone/fork this repo and wire up the `local_repository` rule to your local copy of gapic-generator-go and run `bazel build :echo_go_gapic` from the project root. It's all in the README.

https://github.com/noahdietz/bazel-microgen-test

**Comment by noahdietz** [comment]
I added a sample config but I'm not sure if it will work. We are learning together!

Also, I'm not sure if the implementation of go_gapic_library here will properly package the generated sample files too 🤷‍♂. LMK what you find.

**Comment by idoqo** [comment]
> I added a sample config but I'm not sure if it will work. We are learning together!
> 
> Also, I'm not sure if the implementation of go_gapic_library here will properly package the generated sample files too man_shrugging. LMK what you find.

I was able to generate the sample using `gen-go-sample` after modifying the `echo_sample.yaml` config a bit (using the [config files here](https://github.com/googleapis/googleapis/tree/master/google/cloud/language/v1) as reference). I couldn't get it to work when invoked as a protoc plugin though, and building with bazel only seems to generate the `bazel-out` folders so I don't think it generates the samples either.

**Comment by idoqo** [comment]
> It's looking great! I left a single comment about the `sample-only` flag. I will push a small repo to my personal account that you can fork and use to test the `go_gapic_library` rule. I'll notify you here when that happens.

Thanks a lot. I've updated it now.

**Comment by noahdietz** [comment]
@idoqo can you open a PR from your fork with your changes to the bazel rules? It'll be easier to comment on things. Thanks! I'll double check the sample generation stuff myself and get back to you.
