### ISSUE TITLE
chore: CI should test with bazel

### ISSUE THREAD

**Issue by noahdietz** [googleapis/gapic-generator-go#236]
In order to validate that the bazel build still works, CI should also test via `bazel test...`

**Comment by vam-google** [comment]
@noahdietz Which CI are you planning to use (CircleCI, Kokoro, something else)?

**Comment by noahdietz** [comment]
@vam-google we use CircleCI in this repo.

We should discuss this, possibly with other microgen authors adding bazel rules. I'd like to not only run `bazel test //...` but also build a GAPIC to test that the generation rule works. 

One idea is to add these rules to Showcase, pull that repo as part of CI and attempt to generate micro-GAPICs via bazel from there as the smoketest. Just an idea.
