### ISSUE TITLE
Json output is not jsonpb formatted, so is incompatible with from_file input

### ISSUE THREAD

**Issue by tprice11** [googleapis/gapic-generator-go#336]
The output messages printed using the `--json` flag use raw json encoding, whereas the parser used when providing a json file via `--from_file` uses a jsonpb to unmarshal.
Usually this works fine except for well known messages such as [Duration](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/duration.proto#L92)  which should encode into a json string instead of just the object, leading to an output which doesn't work as an input.

Eg for a type foo with a duration field, `gapicclient get-foo --name=foo1 > foo.json` followed by `gapic update-foo --from_file=foo.json` will fail with `json: cannot unmarshal object into Go value of type string`.

PR to follow.

**Comment by noahdietz** [comment]
Released in v0.12.3.
