### ISSUE TITLE
gapic: Support (google.api.field_behavior) = REQUIRED

### ISSUE THREAD

**Issue by robsonmeemo** [googleapis/gapic-generator-go#376]
Generate special client methods that encode in their method signature that a certain field is required by that request.

**Comment by noahdietz** [comment]
Hi @robsonmeemo thanks for opening the feature request and for using gapic-generator-go.

We won't be able to implement this as it would be a backwards-incompatible behavioral change in existing generated client libraries. While an API might be validating the payload similarly and returning an API error, this change would move payload validation into the client, which would emit a different error and potentially break user error handling code, tests, etc.

This might be something that is revisited, especially if some other potential breaking changes we have are planned, but for now I am going to close this. If you have more questions or want guidance on how to implement it in a fork, feel free to follow up on this issue.

**Comment by robsonmeemo** [comment]
Please see https://aip.dev/client-libraries/4232 for reference.

Note that I said "special client methods". I'm not proposing changing the behavior of existing methods. Unfortunately Go doesn't have method overloads, but there could be still special methods for example:

```
message TranslateTextRequest {
  // The text to translate.
  string q = 1 [(google.api.field_behavior) = REQUIRED];
  string target_lang;
}

service TranslateService {
  rpc TranslateText(TranslateTextRequest) returns (TranslateTextResponse) {
    option (google.api.method_signature) = "q,target_lang";
  }
}
```

```
func (s *TranslateService) TranslateText(req *TranslateTextRequest) (*TranslateTextResponse, error)

func (s *TranslateService) TranslateTextWithSignature(q string, targetLang *string) (*TranslateTextResponse, error)
```

**Comment by noahdietz** [comment]
Thanks @robsonmeemo I'm aware of the AIP and thanks for referencing it. The AIP does not state that a client library generator **must** implement `method_signature` support nor do the other AIPs state that `field_behavior` **must** be supported. We have chosen not to support these features for Go.

How would you qualify "special clients" or "special RPCs"?

In my experience, inferred "special behavior" makes it difficult to convey to API producers what will trigger a generation feature, and what will result in a breaking change - which supporting some special combination of `method_signature` and `field_behavior` certainly opens us up to. We have experienced this, and dealt with unpleasant breaking changes as a result.

Is there some specific feedback for an existing client library that you think would benefit from this? Is this a feature you'd like to see add for generation of your own API client library?

**Comment by robsonmeemo** [comment]
I didn't say "special clients" or "special RPCs". I said "special client methods" or just "special methods". These would be extra methods like I gave an example above. You can also see the Kotlin generator that generates these special methods as overloads.

I'm interested in generating a client for my own service API.
