### ISSUE TITLE
Update go-gapic-package & grpc-service-config options to support multiple mode

### ISSUE THREAD

**Issue by valery-barysok** [googleapis/gapic-generator-go#449]
It will be great to make it possible to generate clients from multiple packages with single command:
```
	protoc \
		-I ${API_COMMON_PROTOS} \
		-I ${EXAMPLEAPIS} \
		--go_gapic_out=. \
		--go_gapic_opt="go-gapic-package=pkg1/apiv1"';pkg1' \
		--go_gapic_opt="grpc-service-config=${EXAMPLEAPIS}/example/pkg1/v1/pkg1_grpc_service_config.json" \
		--go_gapic_opt="go-gapic-package=pkg2/apiv1"';pkg2' \
		--go_gapic_opt="grpc-service-config=${EXAMPLEAPIS}/example/pkg2/v1/pkg2_grpc_service_config.json" \
		${EXAMPLEAPIS}/example/pkg1/v1/*.proto \
		${EXAMPLEAPIS}/example/pkg2/v1/*.proto
```

Other way is to make `go-gapic-package` option inside proto files like `option go_package = ...`:
```
option go_gapic_package = ...
```

and to do something similar for `grpc-service-config` option.

**Comment by noahdietz** [comment]
Hi @valery-barysok thanks for the feature request.

I don't think we'd want to do this. For one, there is no way to map multiple `go-gapic-package` values to the appropriate proto package(s) in the input proto glob. This would require additional config/option syntax. Furthermore, it is possible to define multiple, discrete services in a given `grpc-serivce-config`, so only one file is really necessary.

As for a proto extension, I have no where to host said extension. It can't be added to where the other annotations are defined and anywhere else would require APIs taking an extra dependency. 

At the end of the day, it is trivial to write some bash (or a Go program!) that invokes the protoc plugin with a list of different configs, producing the same result. Thanks but I don't think we should implement this.

**Comment by valery-barysok** [comment]
@noahdietz, you are right about that it is possible to define in one service config file but it is not the case. Just look at googleapis you can find a lot of separate such configs and in my case there are separate service config files in different places. I want to generate everything using single command similar to what I can do with `protoc-gen-go` plugin. I just want the same simplicity. And yes I have bash script that invoke `protoc` compiler many times but it leads to do unnecessary work.

As I said may be it is better to introduce go_gapic_package options for proto files and it is aligned with what we have for `protoc-gen-go`.

**Comment by valery-barysok** [comment]
@noahdietz, I want to add other point: now you can union generation of protobuf message files, grpc clients with single command with latest `protoc-gen-go` and `protoc-gen-go-grpc`.
```
	protoc \
		-I ${API_COMMON_PROTOS} \
		-I ${EXAMPLEAPIS} \
		--go_out=. \
		--go_opt=module=${EXAMPLE_GENPROTO_GO_MODULE} \
		--go-grpc_out=. \
		--go-grpc_opt=module=${EXAMPLE_GENPROTO_GO_MODULE} \
		${EXAMPLEAPIS}/example/pkg1/v1/*.proto \
		${EXAMPLEAPIS}/example/pkg2/v1/*.proto
```
and it will be good idea to support the same behavior for gapic too:

```
	protoc \
		-I ${API_COMMON_PROTOS} \
		-I ${EXAMPLEAPIS} \
		--go_out=. \
		--go_opt=module=${EXAMPLE_GENPROTO_GO_MODULE} \
		--go-grpc_out=. \
		--go-grpc_opt=module=${EXAMPLE_GENPROTO_GO_MODULE} \
		--go_gapic_out=. \
		--go_gapic_opt=module=${EXAMPLE_GENPROTO_GO_MODULE} \
		${EXAMPLEAPIS}/example/pkg1/v1/*.proto \
		${EXAMPLEAPIS}/example/pkg2/v1/*.proto
```
