### ISSUE TITLE
Bad user experience when generate multiple clients at once

### ISSUE THREAD

**Issue by valery-barysok** [googleapis/gapic-generator-go#450]
I would like to get the same user experience as when i use next plugins to be able to combine them with gapic generator in the same command:
```
	_ "google.golang.org/protobuf/cmd/protoc-gen-go"
	_ "google.golang.org/grpc/cmd/protoc-gen-go-grpc"
```

Something like this:

```
      protoc \
		-I ${API_COMMON_PROTOS} \
		-I ${EXAMPLEAPIS} \
		--go_out=. \
		--go-grpc_out=. \
		--go_gapic_out=. \
		${EXAMPLEAPIS}/example/pkg1/v1/*.proto \
		${EXAMPLEAPIS}/example/pkg2/v1/*.proto
```

based on https://github.com/googleapis/gapic-generator-go/issues/449

**Comment by noahdietz** [comment]
Hi @valery-barysok thanks for taking the time to provide feedback, we do appreciate it.

While I understand this might be a real use case, it is not an explicit goal to support generating multiple clients at once, nor is it a goal to ensure that this code generator parallels the Protobuf & gRPC Go code generator usage patterns directly. This generator adheres to the standards set out by [aip.dev/client-libraries](https://aip.dev/client-libraries). While technically possible, it would require designing new configuration or repurposing existing options which would probably complicate the invocation further. I don't think this is a use case we are able to support right now, nor is it a priority at the moment. With that in mind, I don't want to keep this issue open indefinitely when there are no plan to support this. As I mentioned in #449, there are very straightforward solutions to generating multiple clients with this generator that do not require overhauling the generator's configuration. 

Thank you.
