### ISSUE TITLE
gapic: use gRPC transport directly

### ISSUE THREAD

**Issue by pongad** [googleapis/gapic-generator-go#46]
Using generic transport pulls in some HTTP-only dependencies.

**Comment by noahdietz** [comment]
@pongad any more info on what this might look like? Thanks

**Comment by pongad** [comment]
I think our clients are using `google.golang.org/api/transport`'s `DialGrpc` function. I think we can move to `google.golang.org/api/transport/grpc`'s `Dial` instead.

I didn't do this at first since we wanted less diff. Do you think we have enough confidence in new generator to do it now?

**Comment by noahdietz** [comment]
The diffs are very minimal now (default retry config is really the only change). So as far as minimizing noise in the micro-gapics for review, we are there, and @jadekler approved of the diffs. 

So I'd say there isn't anything stopping us from doing this, unless we wanted to wait until we've actually migrated to micro-generator use to then make such a change

**Comment by pongad** [comment]
I don't think waiting for everything is a blocker, though doing this isn't a high priority either. I think do whatever is easiest for you :P If you'd rather get this done so you have one fewer open issue, I think that's reason enough to do it.

**Comment by noahdietz** [comment]
This was essentially fixed in the switch to DialPool.
