### ISSUE TITLE
do not fail if pagination response field does not have repeated fields

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/gapic-generator-go#493]
[AIP-4233](https://google.aip.dev/4233) does not require the generator to fail if the pagination settings cannot be inferred from the request and response messages. If a response method does not contain any repeated fields, my understanding is that it just should not be considered a paginated method.

Code in question:

https://github.com/googleapis/gapic-generator-go/blob/483fa656ddea2ccf18d68e615d9ae78c12cdd4fe/internal/gengapic/paging.go#L148

https://github.com/googleapis/gapic-generator-go/blob/483fa656ddea2ccf18d68e615d9ae78c12cdd4fe/internal/gensample/paging.go#L71

Internal question ID: 9137275878353403904

**Comment by noahdietz** [comment]
Thanks Alex, on it.

**Comment by noahdietz** [comment]
Released in v0.17.0 and I'm updating googleapis.
