### ISSUE TITLE
gapic: include example in package doc

### ISSUE THREAD

**Issue by tbpg** [googleapis/gapic-generator-go#591]
It would be great to have an example of how to get started with the given package in the package doc. During user feedback, some users have had difficulty finding the "entry point" of the package. Let's make it obvious.

For example, cloud.google.com/go/storage (manual client) has many examples at the top: https://pkg.go.dev/cloud.google.com/go/storage

But, generated packages do not: https://pkg.go.dev/cloud.google.com/go/accessapproval/apiv1

**Comment by alicejli** [comment]
@tbpg @codyoss It looks like https://pkg.go.dev/cloud.google.com/go/storage includes the examples through a README.md file. Is that what we want to do for the generated packages? Or is there a way to do it via the doc.go files?

**Comment by codyoss** [comment]
I think @tbpg was saying in the package godoc. Here is a link to an examlpe: https://pkg.go.dev/cloud.google.com/go/storage#hdr-Creating_a_Client https://github.com/googleapis/google-cloud-go/blob/7fd2ccd26adec1468e15fe84bf75210255a9dfea/storage/doc.go#L32-L40
