### ISSUE TITLE
gapic: include link to GoDoc for request types in examples

### ISSUE THREAD

**Issue by tbpg** [googleapis/gapic-generator-go#638]
Our examples leave a TODO to fill in request fields. It would be helpful to give users a link where they can see all of the fields of that type.

(Better would be to add placeholders for all of the right fields, but we don't know what all of the right fields are.)

**Comment by noahdietz** [comment]
> It would be helpful to give users a link where they can see all of the fields of that type.

I like it, but doesn't GoDoc link the request type in the method definition already? 

> Better would be to add placeholders for all of the right fields, but we don't know what all of the right fields are.

Well, we could generate _all_ fields in the request message, but that could get out of hand. There are some hints from the google.api.field_behavior annotations, some fields are annotated as Required, others Output Only. It's not a strictly required annotation, so I have a feeling we'd miss some fields if they are unannotated but are commented as Required. I think a user might be better served with a link to the Request message, where all of the field documentation is as well (including which are required and output only). 

WDYT?

**Comment by tbpg** [comment]
> doesn't GoDoc link the request type in the method definition already?

Not for examples. See https://pkg.go.dev/cloud.google.com/go/bigquery@v1.18.0/connection/apiv1#example-Client.CreateConnection.

There are generally two options I see:
1. Link to docs, which isn't very helpful, but it's not wrong.
2. Guess the required fields, which is more helpful, but sometimes wrong.

I'd vote for option 1 -- not as helpful, but never wrong.

**Comment by noahdietz** [comment]
> Not for examples.

Yeah, but the method doc is right next to the example and it has a link to the type. I'm OK with doing this, just wondering if it is duplicated & slightly less usable (have to copy paste the link) information.

> I'd vote for option 1 -- not as helpful, but never wrong.

Agreed.
