### ISSUE TITLE
cleanup: protobuf dependency

### ISSUE THREAD

**Issue by software-dov** [googleapis/gapic-generator-go#667]
The protobuf dependency in many parts of the code base are `"github.com/golang/protobuf/proto"`
This is a cleanup tracking issue to change those to `"google.golang.org/protobuf/proto"`

**Comment by noahdietz** [comment]
Note: We cannot completely remove `github.com/golang/protobuf` from the codebase as our plugin is built using the v1 module's plugin interface (see #348). But wherever we are using helpers from `github.com/golang/protobuf/proto`, we can definitely swap it out for the v2 module. I think this mostly appears in test files. Let's do this during the fixit.
