### ISSUE TITLE
Fix Showcase integration test failures

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/gapic-generator-go#671]
After syncing with the fixes currently in this [fork](https://github.com/software-dov/gapic-generator-go/tree/test-fixings) and then locally applying #670, the Showcase integration tests show some failures. We need to fix them ASAP, because if they reveal bugs in the Go generator implementation, then they are a release blocker, and if they reveal bugs in Showcase, that is a major inconvenience as Showcase is intended to help validate generator implementations.

To reproduce:

In gapic-showcase:
```
gapic-showcase run |& tee /tmp/showcase.server.txt
```

In gapic-generator-go,
```
go test ./... |& tee /tmp/showcase.goclient.txt
```

Looking at the client and server logs thus generated, it seems that the errors are coming from `repeat:query` and `repeat:simplepath`. Two things immediately jump out:
- `repeat:query` requests received by the server are empty
- `repeat:simplepath` requests received by the server have `serverVerify: false` which is not how they're configured in the compliance sutie file.

**Comment by vchudnov-g** [comment]
`repeat.simplepath` uses dotted fields in the URL path params
`repeat:query` uses dotted fields in the query params

As @vam-google pointed out, neither of these occur in the synthetic protos we use for GCE. So, I suggest:
1. Disable failing on these two requests and see whether we have any other failures running against Showcase, and then post the results here.
   1. If we do have other failures, let's discuss and prioritize
   2. if we don't have other failures, we can drop priority to p2, and release an initial GCE client.
2. Regardless, all these failures should eventually be fixed, but maybe they don't need to block our imminent releases.

**Comment by noahdietz** [comment]
What's up with this?

**Comment by vchudnov-g** [comment]
Lowering priority to P2, since this isn't blocking our imminent releases. However, we should check that the other test cases pass. I believe @software-dov already verified this, correct?

**Comment by software-dov** [comment]
I believe that the non-resource showcase tests all pass now.
https://github.com/googleapis/gapic-generator-go/blob/master/showcase/compliance_test.go#L60

**Comment by vchudnov-g** [comment]
Great. Closing this, then.
