### ISSUE TITLE
gapic: metadata JSON diffs on whitespace and its rather annoying

### ISSUE THREAD

**Issue by noahdietz** [googleapis/gapic-generator-go#691]
Example of the gapic_metadata.json diffing on whitespace: https://github.com/googleapis/google-cloud-go/pull/4360/files/a666083de1a4f4245473d79a5cb2eba701815169#r662355143. This shouldn't happen.

**Comment by codyoss** [comment]
@noahdietz `protojson` on purpose provides non-deterministic json out(with whitespace) so users don't rely on its output. I am not sure it is documented but you can at least see this mentioned in the issue tracker. I only know this because I have been down this rabbit hole before 😸

**Comment by noahdietz** [comment]
haha well boo! Thanks, I will try to figure something out...
