### ISSUE TITLE
unable to generate filestore.v1 do to LRO metadata

### ISSUE THREAD

**Issue by codyoss** [googleapis/gapic-generator-go#707]
Ran:

```bash
protoc -I /var/folders/0z/m6tbcywj3s33d95zg0326szr00nsl6/T/update-genproto448712005/googleapis \
-I /var/folders/0z/m6tbcywj3s33d95zg0326szr00nsl6/T/update-genproto448712005/googleapis-discovery \
--experimental_allow_proto3_optional -I /var/folders/0z/m6tbcywj3s33d95zg0326szr00nsl6/T/update-genproto448712005/proto \
--go_gapic_out /path/google-cloud-go \
--go_gapic_opt go-gapic-package=cloud.google.com/go/filestore/apiv1;filestore \
--go_gapic_opt api-service-config=google/cloud/filestore/v1/file_v1.yaml \
--go_gapic_opt release-level=beta \
--go_gapic_opt grpc-service-config=google/cloud/filestore/v1/file_grpc_service_config.json \
--go_gapic_opt metadata \
/var/folders/0z/m6tbcywj3s33d95zg0326szr00nsl6/T/update-genproto448712005/googleapis/google/cloud/filestore/v1/cloud_filestore_service.proto
```

Error:

```bash
unable to resolve google.longrunning.operation_info.metadata_type value "google.cloud.common.OperationMetadata" in rpc "google.cloud.filestore.v1.CloudFilestoreManager.CreateBackup"
```

Related: https://github.com/googleapis/gapic-generator-python/issues/932

**Comment by codyoss** [comment]
cc @noahdietz

**Comment by noahdietz** [comment]
Thanks we are aware of this and we are working on a solution. For now, please punt on generation of this.

**Comment by noahdietz** [comment]
Repro from the root of googleapis, run:
```
protoc -I. \
--go_gapic_out $CLOUD_GO \
--go_gapic_opt module=cloud.google.com/go \
--go_gapic_opt "go-gapic-package=cloud.google.com/go/filestore/apiv1;filestore" \
--go_gapic_opt api-service-config=google/cloud/filestore/v1/file_v1.yaml \
--go_gapic_opt release-level=beta \
--go_gapic_opt grpc-service-config=google/cloud/filestore/v1/file_grpc_service_config.json \
--go_gapic_opt metadata \
google/cloud/filestore/v1/cloud_filestore_service.proto
```

where `$CLOUD_GO` is the path to a local clone of https://github.com/googleapis/google-cloud-go.

**Comment by noahdietz** [comment]
The proto is missing the import for `google/cloud/common/operation_metadata.proto`. Adding that import fixes Go generation. That should be fixed upstream in the publishing tools. I will keep this open until that is fixed and we can begin generating it.

**Comment by danoscarmike** [comment]
@hkdevandla for vis.

This is on our critical path now. Can we please prioritize the fix? LMK if/how I can help.

**Comment by hkdevandla** [comment]
@noahdietz can you check if the fix is in place so we can generate the libs? Thanks!

**Comment by noahdietz** [comment]
Ack. I will look today.

**Comment by noahdietz** [comment]
Ok, to reiterate, this is not a Go specific problem, but rather a problem in the proto publishing pipeline. Is there an internal bug tracking generation for this API that we can open a blocking bug against instead? This isn't the right place to track the work. Feel free to ping me offline too.

**Comment by noahdietz** [comment]
We have two options:
A. We "teach" every generator to read `metadata_type: "google.cloud.common.OperationMetadata"` and understand that it comes from `google/cloud/common/operation_metadata.proto` without there being an `import` statement for the proto
B. We update the publishing tools to see `metadata_type: "google.cloud.common.OperationMetadata"` and inject the `import` statement for `google/cloud/common/operation_metadata.proto` in the sanitized versions (allows build_gen to incorporate the bazel dep and protoc plugins to resolve the message type)

B. seems like the better solution, just that it has a couple ways of doing it, some more "idiomatic"/clean than others.

**Comment by codyoss** [comment]
I agree, "B" sounds better. If you want to close this issue in favor of an internal issue please feel free to do so.

**Comment by noahdietz** [comment]
> I agree, "B" sounds better. If you want to close this issue in favor of an internal issue please feel free to do so.

Agreed. Opened 201420299. Closing this.
