### ISSUE TITLE
Support external authentication tokens

### ISSUE THREAD

**Issue by drewwells** [googleapis/gapic-generator-go#795]
**Is your feature request related to a problem? Please describe.**
We would like to generate gRPC clients from our protobufs using gapic. In order to authorize calls, this client needs to support our mechanism for passing along headers/grpc metadata.

**Describe the solution you'd like**
An option to interrogate a variable or better yet a method for returning a gRPC metadata for authorizing calls.

**Describe alternatives you've considered**
Adding our own clientOption, but it relies on an internal packages that we will be unable to implement https://pkg.go.dev/google.golang.org/api@v0.58.0/option#ClientOption

**Comment by noahdietz** [comment]
Clients generated by this plugin are capable of being configured to use a different authentication mechanism. The caller of a generated client may supply `option.ClientOption`s ([godoc](https://pkg.go.dev/google.golang.org/api/option)) that can include various authentication info OR an already-authenticated/already-dialed gRPC connection via `option.WithGRPCConn` ([godoc](https://pkg.go.dev/google.golang.org/api/option#WithGRPCConn)).

Nothing in the generator needs to change to support this. `Dial` ([godoc](https://pkg.go.dev/google.golang.org/api/transport/grpc#Dial)) will respect client options. There may be some issues if piece meal options are povided, best bet is providing your own connection.
