### ISSUE TITLE
CLI Gen fails on repeated bytes field.

### ISSUE THREAD

**Issue by landrito** [googleapis/gapic-generator-go#81]
For gapic-showcase, the following line was produced. I think the main culprit is the `[]` before ByteSliceVar.
```go
VerifyTestCmd.Flags().[]ByteSliceVar(&VerifyTestInput.Answers, "answers", [][]byte{}, "")
```

**Comment by landrito** [comment]
Looking into pflags. It doesn't look like they support `[][]byte` as a flag, which makes sense. I'd probably just add a check to see if it's a repeated bytes field and if so, just denote that it can only be passed through json file.

**Comment by noahdietz** [comment]
Thanks for looking into this! You're totally right. I'll have a fix for this soon. 

Which proto introduced this? I need to make sure my testing showcase protos are up-to-date...

**Comment by landrito** [comment]
It was a recent change to the testing proto in gapic-showcase. I'll have a v0.0.10 release soon with it included.
