### ISSUE TITLE
gencli: nested message oneof field of Message type naming is borked

### ISSUE THREAD

**Issue by noahdietz** [googleapis/gapic-generator-go#84]
Testing against the Vision API resulted in a broken CLI.

product_search_service.ImportProductSetsRequest.input_config of type ImportProductSetsInputConfig is a nested message and has a oneof field of type Message.

All of the associated naming for it is borked. 

Ultimately, we need to find a better way of generating naming & variable references, its too hacky right now.

**Comment by sandipbhuyan** [comment]
hi @noahdietz  I want to work in this issue. If it is free to pick

**Comment by noahdietz** [comment]
@sandipbhuyan thanks for taking a look at this. I believe this might require some far reaching changes to how variable naming is done in GCLIs. Like the issue says, I kind of hacked it together.

If you want to take a crack at it, please feel free. But I would prefer we discuss the approach that will be taken here in the issue. If you have an idea, please share it. I'd like to agree on something before a PR is sent. Thanks for your interest!

**Comment by noahdietz** [comment]
The example issue provided in the original comment is resolved by #132. However, after attempting to generate CLIs for more Cloud APIs, many were too complex. The generated output was 1. not compilable 2. way too complex for command line consumption. As such, I believe it is reasonable to say that not every API will be able to have a `gcli` and close this issue.
